# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Holiday Friends' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'SVProgressHUD'
  pod 'SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'SkyFloatingLabelTextField'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'FSCalendar'
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'
  pod 'Google-Maps-iOS-Utils'
  pod 'GooglePlaces', '3.10.0'
  pod 'Firebase/Auth'
  pod 'Firebase'
  pod 'GooglePlacesSearchController'
  pod 'FBSDKLoginKit'
  pod 'FirebaseMessaging'
  pod 'SDWebImageSVGCoder'
  
  target 'Holiday FriendsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Holiday FriendsUITests' do
    # Pods for testing
  end

end
